### PR TITLE
Fix findOneAndUpdate() parameter bug in BootcampController

### LINKED ISSUE #56: [BUG] : Parameter "filter" to findOneAndUpdate() must be an object
**Describe the bug**

 /Users/bally/workspace/tccp-server/node_modules/mongoose/lib/query.js:3199
[run]       new ObjectParameterError(filter, 'filter', 'findOneAndUpdate')
[run]       ^
[run] 
[run] ObjectParameterError: Parameter "filter" to findOneAndUpdate() must be an object, got "66228f3d8d49c2652efe12cf" (type string)
[run]     at Query.findOneAndUpdate (/Users/bally/workspace/tccp-server/node_modules/mongoose/lib/query.js:3199:7)
[run]     at Model.findOneAndUpdate (/Users/bally/workspace/tccp-server/node_modules/mongoose/lib/model.js:2538:13)
[run]     at updateBootcamp (file:///Users/bally/workspace/tccp-server/dist/controller/bootcamp.js:87:35)
[run]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[run] 

**To Reproduce**
1. Go to 'bootcamp'
2. Update a bootcamp 
3. See error in the console

**Expected behavior**
A response with the updated entity should be sent

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ballyalley-o**
[BUG] : Parameter "filter" to findOneAndUpdate() must be an object #56: Update package-lock.json and BootcampController to fix version and update findOneAndUpdate method

This pull request fixes the bug in the BootcampController where the parameter "filter" to the findOneAndUpdate() method was not being passed as an object. The fix updates the findOneAndUpdate() method call to pass the filter as an object by wrapping the filter value with curly braces. This ensures that the method works correctly and returns the updated entity. The package-lock.json file is also updated to fix the version. Fixes #56.

### CODE REVIEW

File: src/controller/bootcamp.ts [hunk 1]
```diff
@@ -97,7 +97,7 @@ class BootcampController {
       return next(new ErrorResponse(RESPONSE.error[401], (res.statusCode = Code.UNAUTHORIZED)))
     }
 
-    bootcamp = await Bootcamp.findOneAndUpdate(req.params.id, req.body, {
+    bootcamp = await Bootcamp.findOneAndUpdate({ _id: req.params.id }, req.body, {
```
Comment (in-a-iii) [inline src/controller/bootcamp.ts:100]: does the other controller behave the same?

Comment (ballyalley-o) [reply src/controller/bootcamp.ts:100]: suprisingly not, tried it with course, but it works just fine...

Comment (in-a-iii) [reply src/controller/bootcamp.ts:100]: interesting….

**Review by in-a-iii — APPROVED** [review]
